// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/tuxmonteiro/tks-compliance-controller/pkg/apis/tks/v1alpha1.TksComplianceMonitor":       schema_pkg_apis_tks_v1alpha1_TksComplianceMonitor(ref),
		"github.com/tuxmonteiro/tks-compliance-controller/pkg/apis/tks/v1alpha1.TksComplianceMonitorSpec":   schema_pkg_apis_tks_v1alpha1_TksComplianceMonitorSpec(ref),
		"github.com/tuxmonteiro/tks-compliance-controller/pkg/apis/tks/v1alpha1.TksComplianceMonitorStatus": schema_pkg_apis_tks_v1alpha1_TksComplianceMonitorStatus(ref),
	}
}

func schema_pkg_apis_tks_v1alpha1_TksComplianceMonitor(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "TksComplianceMonitor is the Schema for the tkscompliancemonitors API",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/tuxmonteiro/tks-compliance-controller/pkg/apis/tks/v1alpha1.TksComplianceMonitorSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/tuxmonteiro/tks-compliance-controller/pkg/apis/tks/v1alpha1.TksComplianceMonitorStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/tuxmonteiro/tks-compliance-controller/pkg/apis/tks/v1alpha1.TksComplianceMonitorSpec", "github.com/tuxmonteiro/tks-compliance-controller/pkg/apis/tks/v1alpha1.TksComplianceMonitorStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_tks_v1alpha1_TksComplianceMonitorSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "TksComplianceMonitorSpec defines the desired state of TksComplianceMonitor",
				Type:        []string{"object"},
			},
		},
	}
}

func schema_pkg_apis_tks_v1alpha1_TksComplianceMonitorStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "TksComplianceMonitorStatus defines the observed state of TksComplianceMonitor",
				Type:        []string{"object"},
			},
		},
	}
}
